spring:
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://192.168.80.128:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #对象存储
    alicloud:
      access-key: LTAI5tNX9ePQ1DCjfmHU2Dcn
      secret-key: uImSmBbJHV1u2cHZastJCSvzIxTrM1
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com


  application:
    name: gulimall-product
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      #logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 10001
#打印sql
logging:
  level:
    com.atguigu.gulimall: debug

